### ISSUE TITLE
PA Review: Heroku Deployment

### ISSUE THREAD

**Issue by English3000** [English3000/fakebook#1]
See: [Fakebook on Heroku](https://fakebook-fullstack.herokuapp.com/)

**Comment by English3000** [comment]
Component isn't rendering; & hit [hourly limit](https://devcenter.heroku.com/articles/limits#build) for pushing to Heroku.

**Comment by English3000** [comment]
Added Procfile w/ `web: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}`. Adding this seems to make it preempt `webpack`.

**Comment by dobrynin** [comment]
👍
