### ISSUE TITLE
PA Review: Frontend Auth

### ISSUE THREAD

**Issue by English3000** [English3000/fakebook#2]

**Comment by English3000** [comment]
heroku Frontend Auth won't sign in or up even though local one works. 500 server error.

** Issue was didn't do `heroku run rails db:migrate`

**Comment by English3000** [comment]
Ran `heroku pg:reset`.

Tried `heroku run rails db:setup`--_ERROR: FATAL:  permission denied for database "postgres"
DETAIL:  User does not have CONNECT privilege._

** Resolved. Correct command was `heroku run rails db:migrate`

**Comment by English3000** [comment]
Sign In & Demo buttons don't sign in on heroku, but they work on localhost:3000.

** Resolved: Ran `heroku run rails db:seed`
-> Images won't render until AWS/Paperclip setup complete

**Comment by chungkikelly** [comment]
Frontend + Backend auth are good to go. Please note that pressing `enter` to submit the session form information doesn't seem to intuitively `Sign Up` or `Sign In`.

This feature will be considered complete for now - please consider revisiting the feature if time permits.

**Comment by English3000** [comment]
One thought would be to make the box-shadow appear on the Sign In button when either input is in focus.

**Comment by chungkikelly** [comment]
That may work - regardless, we shall revisit this topic after the rest of the MVP's are completed.
