### ISSUE TITLE
PA Review: User Show (Profile) Page

### ISSUE THREAD

**Issue by English3000** [English3000/fakebook#3]

**Comment by chungkikelly** [comment]
Does a user's profile page contain anything other than a profile photo + cover photo?

If not, please consider adding additional information about the user. Facebook typically attempts to gather + display more information about each user.

It would just take some modifications of the DB schema + adding a couple more HTML / CSS elements to fill the page out a bit more.

**Comment by English3000** [comment]
So add an Intro box?

I'll add the Friends box once I get to that MVP.

**Comment by chungkikelly** [comment]
Exactly. I don't use Facebook anymore, but if memory serves, it displays where you work, went to school, where you love, and relationship status. 

The thing about cloning Facebook is that everyone has an expectation of what the site contains. So if your goal is to create a clone, then you should strive to add details like the intro + friend box.

**Comment by English3000** [comment]
Will do. Friending is its own MVP.

**Comment by chungkikelly** [comment]
I'm going to unassign myself from this MVP. Please re assign when it's ready to be reviewed.

**Comment by chungkikelly** [comment]
Please add a bit more seed data, so it's not just you and the demo user.
