### ISSUE TITLE
PA Review: Commenting/Posting (on each others' walls)

### ISSUE THREAD

**Issue by English3000** [English3000/fakebook#5]
One note: posting to another user's wall will display the post; but navigating elsewhere and then returning to their wall, the post will no longer be there.

Not sure if this is part of the MVP. David gave me the impression that it wasn't (as he said I wouldn't need a `walls` table).

**Comment by chungkikelly** [comment]
Can you check to see whether or not there are additional comments on another user's wall in the Production DB?

**Comment by chungkikelly** [comment]
I wonder if you're just dispatching the action to receive the comment on the frontend, but don't actually make an AJAX request to create the comment in the back end

**Comment by chungkikelly** [comment]
After further review, the comment appears in my own feed and appears on the friends wall at that moment. But, on refresh, the comment disappears from my friend's wall, but remains in my own feed. Weird - perhaps we're just not fetching the comments properly?

Will unassign myself - please assign when the issue's been resolved.

**Comment by English3000** [comment]
That is as instructed… I had the idea of a wall table so that other users’ posts could appear on a friend’s wall too. Maybe adding a foreign key on posts and a model association could also allow for this functionality.
